# Generated by Django 2.1.2 on 2019-03-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BDetect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_value', models.CharField(max_length=200)),
                ('cookie_expiration', models.DateTimeField(verbose_name='Cookie Expiration')),
            ],
        ),
    ]
