# Generated by Django 2.1.2 on 2019-03-10 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webAPI', '0003_auto_20190310_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='productID',
            field=models.CharField(default=django.utils.timezone.now, max_length=6, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
