# Generated by Django 2.1.2 on 2019-03-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAPI', '0004_auto_20190310_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('basketID', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('basketExpiry', models.DateTimeField(verbose_name='Basket Expiration')),
                ('basketItem', models.ManyToManyField(to='webAPI.Product')),
            ],
        ),
    ]
