# Generated by Django 2.1.2 on 2019-03-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAPI', '0005_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='basketQty',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
