# Generated by Django 2.1.2 on 2019-03-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAPI', '0006_basket_basketqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productPrice',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=6),
            preserve_default=False,
        ),
    ]
