# Generated by Django 2.1.2 on 2019-03-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAPI', '0007_product_productprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='basketTotal',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
            preserve_default=False,
        ),
    ]
